"""create prevent_records table

Revision ID: a1b97dee88c0
Revises: 
Create Date: 2026-03-25 21:04:44.136549
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a1b97dee88c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prevent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.Column('patient_sex', sa.String(length=20), nullable=False),
    sa.Column('patient_country', sa.String(length=100), server_default=sa.text("'Ecuador'"), nullable=False),
    sa.Column('patient_province', sa.String(length=100), nullable=True),
    sa.Column('total_cholesterol', sa.Float(), nullable=True),
    sa.Column('hdl_cholesterol', sa.Float(), nullable=True),
    sa.Column('ldl_cholesterol', sa.Float(), nullable=True),
    sa.Column('systolic_bp', sa.Float(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('smoker', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('egfr', sa.Float(), nullable=True),
    sa.Column('statin_use', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('antihypertensive_use', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('physician_name', sa.String(length=150), nullable=False),
    sa.Column('physician_specialty', sa.String(length=150), nullable=False),
    sa.Column('physician_city', sa.String(length=100), nullable=True),
    sa.Column('risk_10y', sa.Float(), nullable=True),
    sa.Column('risk_category', sa.String(length=50), nullable=True),
    sa.Column('engine_version', sa.String(length=100), server_default=sa.text("'AHA_PREVENT_original_adapted'"), nullable=False),
    sa.Column('source_org', sa.String(length=150), server_default=sa.text("'ANOVA Research Group'"), nullable=False),
    sa.Column('initiative_name', sa.String(length=150), server_default=sa.text("'Red Ecuatoriana de Cardiometabolismo DOH'"), nullable=False),
    sa.Column('director_name', sa.String(length=150), server_default=sa.text("'Dr. David Guzmán'"), nullable=False),
    sa.Column('consent_for_research', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('input_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prevent_records', schema='public')
    # ### end Alembic commands ###
