export type EcuadorProvince = {
  code: string;
  name: string;
};

export type EcuadorCanton = EcuadorProvince & {
  provinceCode: string;
};

// INEC/DPA Ecuador, Clasificador Geografico Estadistico 2024. No incluye parroquias.
export const ECUADOR_PROVINCES: EcuadorProvince[] = [
  { code: "01", name: "AZUAY" },
  { code: "02", name: "BOLÍVAR" },
  { code: "03", name: "CAÑAR" },
  { code: "04", name: "CARCHI" },
  { code: "05", name: "COTOPAXI" },
  { code: "06", name: "CHIMBORAZO" },
  { code: "07", name: "EL ORO" },
  { code: "08", name: "ESMERALDAS" },
  { code: "09", name: "GUAYAS" },
  { code: "10", name: "IMBABURA" },
  { code: "11", name: "LOJA" },
  { code: "12", name: "LOS RÍOS" },
  { code: "13", name: "MANABÍ" },
  { code: "14", name: "MORONA SANTIAGO" },
  { code: "15", name: "NAPO" },
  { code: "16", name: "PASTAZA" },
  { code: "17", name: "PICHINCHA" },
  { code: "18", name: "TUNGURAHUA" },
  { code: "19", name: "ZAMORA CHINCHIPE" },
  { code: "20", name: "GALÁPAGOS" },
  { code: "21", name: "SUCUMBÍOS" },
  { code: "22", name: "ORELLANA" },
  { code: "23", name: "SANTO DOMINGO DE LOS TSÁCHILAS" },
  { code: "24", name: "SANTA ELENA" },
];

export const ECUADOR_CANTONS: EcuadorCanton[] = [
  { code: "0101", name: "CUENCA", provinceCode: "01" },
  { code: "0102", name: "GIRÓN", provinceCode: "01" },
  { code: "0103", name: "GUALACEO", provinceCode: "01" },
  { code: "0104", name: "NABÓN", provinceCode: "01" },
  { code: "0105", name: "PAUTE", provinceCode: "01" },
  { code: "0106", name: "PUCARÁ", provinceCode: "01" },
  { code: "0107", name: "SAN FERNANDO", provinceCode: "01" },
  { code: "0108", name: "SANTA ISABEL", provinceCode: "01" },
  { code: "0109", name: "SÍGSIG", provinceCode: "01" },
  { code: "0110", name: "OÑA", provinceCode: "01" },
  { code: "0111", name: "CHORDELEG", provinceCode: "01" },
  { code: "0112", name: "EL PAN", provinceCode: "01" },
  { code: "0113", name: "SEVILLA DE ORO", provinceCode: "01" },
  { code: "0114", name: "GUACHAPALA", provinceCode: "01" },
  { code: "0115", name: "CAMILO PONCE ENRÍQUEZ", provinceCode: "01" },
  { code: "0201", name: "GUARANDA", provinceCode: "02" },
  { code: "0202", name: "CHILLANES", provinceCode: "02" },
  { code: "0203", name: "CHIMBO", provinceCode: "02" },
  { code: "0204", name: "ECHEANDÍA", provinceCode: "02" },
  { code: "0205", name: "SAN MIGUEL", provinceCode: "02" },
  { code: "0206", name: "CALUMA", provinceCode: "02" },
  { code: "0207", name: "LAS NAVES", provinceCode: "02" },
  { code: "0301", name: "AZOGUES", provinceCode: "03" },
  { code: "0302", name: "BIBLIÁN", provinceCode: "03" },
  { code: "0303", name: "CAÑAR", provinceCode: "03" },
  { code: "0304", name: "LA TRONCAL", provinceCode: "03" },
  { code: "0305", name: "EL TAMBO", provinceCode: "03" },
  { code: "0306", name: "DÉLEG", provinceCode: "03" },
  { code: "0307", name: "SUSCAL", provinceCode: "03" },
  { code: "0401", name: "TULCÁN", provinceCode: "04" },
  { code: "0402", name: "BOLÍVAR", provinceCode: "04" },
  { code: "0403", name: "ESPEJO", provinceCode: "04" },
  { code: "0404", name: "MIRA", provinceCode: "04" },
  { code: "0405", name: "MONTÚFAR", provinceCode: "04" },
  { code: "0406", name: "SAN PEDRO DE HUACA", provinceCode: "04" },
  { code: "0501", name: "LATACUNGA", provinceCode: "05" },
  { code: "0502", name: "LA MANÁ", provinceCode: "05" },
  { code: "0503", name: "PANGUA", provinceCode: "05" },
  { code: "0504", name: "PUJILÍ", provinceCode: "05" },
  { code: "0505", name: "SALCEDO", provinceCode: "05" },
  { code: "0506", name: "SAQUISILÍ", provinceCode: "05" },
  { code: "0507", name: "SIGCHOS", provinceCode: "05" },
  { code: "0601", name: "RIOBAMBA", provinceCode: "06" },
  { code: "0602", name: "ALAUSÍ", provinceCode: "06" },
  { code: "0603", name: "COLTA", provinceCode: "06" },
  { code: "0604", name: "CHAMBO", provinceCode: "06" },
  { code: "0605", name: "CHUNCHI", provinceCode: "06" },
  { code: "0606", name: "GUAMOTE", provinceCode: "06" },
  { code: "0607", name: "GUANO", provinceCode: "06" },
  { code: "0608", name: "PALLATANGA", provinceCode: "06" },
  { code: "0609", name: "PENIPE", provinceCode: "06" },
  { code: "0610", name: "CUMANDÁ", provinceCode: "06" },
  { code: "0701", name: "MACHALA", provinceCode: "07" },
  { code: "0702", name: "ARENILLAS", provinceCode: "07" },
  { code: "0703", name: "ATAHUALPA", provinceCode: "07" },
  { code: "0704", name: "BALSAS", provinceCode: "07" },
  { code: "0705", name: "CHILLA", provinceCode: "07" },
  { code: "0706", name: "EL GUABO", provinceCode: "07" },
  { code: "0707", name: "HUAQUILLAS", provinceCode: "07" },
  { code: "0708", name: "MARCABELÍ", provinceCode: "07" },
  { code: "0709", name: "PASAJE", provinceCode: "07" },
  { code: "0710", name: "PIÑAS", provinceCode: "07" },
  { code: "0711", name: "PORTOVELO", provinceCode: "07" },
  { code: "0712", name: "SANTA ROSA", provinceCode: "07" },
  { code: "0713", name: "ZARUMA", provinceCode: "07" },
  { code: "0714", name: "LAS LAJAS", provinceCode: "07" },
  { code: "0801", name: "ESMERALDAS", provinceCode: "08" },
  { code: "0802", name: "ELOY ALFARO", provinceCode: "08" },
  { code: "0803", name: "MUISNE", provinceCode: "08" },
  { code: "0804", name: "QUININDÉ", provinceCode: "08" },
  { code: "0805", name: "SAN LORENZO", provinceCode: "08" },
  { code: "0806", name: "ATACAMES", provinceCode: "08" },
  { code: "0807", name: "RÍOVERDE", provinceCode: "08" },
  { code: "0901", name: "GUAYAQUIL", provinceCode: "09" },
  { code: "0902", name: "ALFREDO BAQUERIZO MORENO (JUJÁN)", provinceCode: "09" },
  { code: "0903", name: "BALAO", provinceCode: "09" },
  { code: "0904", name: "BALZAR", provinceCode: "09" },
  { code: "0905", name: "COLIMES", provinceCode: "09" },
  { code: "0906", name: "DAULE", provinceCode: "09" },
  { code: "0907", name: "DURÁN", provinceCode: "09" },
  { code: "0908", name: "EL EMPALME", provinceCode: "09" },
  { code: "0909", name: "EL TRIUNFO", provinceCode: "09" },
  { code: "0910", name: "MILAGRO", provinceCode: "09" },
  { code: "0911", name: "NARANJAL", provinceCode: "09" },
  { code: "0912", name: "NARANJITO", provinceCode: "09" },
  { code: "0913", name: "PALESTINA", provinceCode: "09" },
  { code: "0914", name: "PEDRO CARBO", provinceCode: "09" },
  { code: "0916", name: "SAMBORONDÓN", provinceCode: "09" },
  { code: "0918", name: "SANTA LUCÍA", provinceCode: "09" },
  { code: "0919", name: "SALITRE (URBINA JADO)", provinceCode: "09" },
  { code: "0920", name: "SAN JACINTO DE YAGUACHI", provinceCode: "09" },
  { code: "0921", name: "PLAYAS", provinceCode: "09" },
  { code: "0922", name: "SIMÓN BOLÍVAR", provinceCode: "09" },
  { code: "0923", name: "CORONEL MARCELINO MARIDUEÑA", provinceCode: "09" },
  { code: "0924", name: "LOMAS DE SARGENTILLO", provinceCode: "09" },
  { code: "0925", name: "NOBOL", provinceCode: "09" },
  { code: "0927", name: "GENERAL ANTONIO ELIZALDE", provinceCode: "09" },
  { code: "0928", name: "ISIDRO AYORA", provinceCode: "09" },
  { code: "1001", name: "IBARRA", provinceCode: "10" },
  { code: "1002", name: "ANTONIO ANTE", provinceCode: "10" },
  { code: "1003", name: "COTACACHI", provinceCode: "10" },
  { code: "1004", name: "OTAVALO", provinceCode: "10" },
  { code: "1005", name: "PIMAMPIRO", provinceCode: "10" },
  { code: "1006", name: "SAN MIGUEL DE URCUQUÍ", provinceCode: "10" },
  { code: "1101", name: "LOJA", provinceCode: "11" },
  { code: "1102", name: "CALVAS", provinceCode: "11" },
  { code: "1103", name: "CATAMAYO", provinceCode: "11" },
  { code: "1104", name: "CELICA", provinceCode: "11" },
  { code: "1105", name: "CHAGUARPAMBA", provinceCode: "11" },
  { code: "1106", name: "ESPÍNDOLA", provinceCode: "11" },
  { code: "1107", name: "GONZANAMÁ", provinceCode: "11" },
  { code: "1108", name: "MACARÁ", provinceCode: "11" },
  { code: "1109", name: "PALTAS", provinceCode: "11" },
  { code: "1110", name: "PUYANGO", provinceCode: "11" },
  { code: "1111", name: "SARAGURO", provinceCode: "11" },
  { code: "1112", name: "SOZORANGA", provinceCode: "11" },
  { code: "1113", name: "ZAPOTILLO", provinceCode: "11" },
  { code: "1114", name: "PINDAL", provinceCode: "11" },
  { code: "1115", name: "QUILANGA", provinceCode: "11" },
  { code: "1116", name: "OLMEDO", provinceCode: "11" },
  { code: "1201", name: "BABAHOYO", provinceCode: "12" },
  { code: "1202", name: "BABA", provinceCode: "12" },
  { code: "1203", name: "MONTALVO", provinceCode: "12" },
  { code: "1204", name: "PUEBLOVIEJO", provinceCode: "12" },
  { code: "1205", name: "QUEVEDO", provinceCode: "12" },
  { code: "1206", name: "URDANETA", provinceCode: "12" },
  { code: "1207", name: "VENTANAS", provinceCode: "12" },
  { code: "1208", name: "VINCES", provinceCode: "12" },
  { code: "1209", name: "PALENQUE", provinceCode: "12" },
  { code: "1210", name: "BUENA FÉ", provinceCode: "12" },
  { code: "1211", name: "VALENCIA", provinceCode: "12" },
  { code: "1212", name: "MOCACHE", provinceCode: "12" },
  { code: "1213", name: "QUINSALOMA", provinceCode: "12" },
  { code: "1301", name: "PORTOVIEJO", provinceCode: "13" },
  { code: "1302", name: "BOLÍVAR", provinceCode: "13" },
  { code: "1303", name: "CHONE", provinceCode: "13" },
  { code: "1304", name: "EL CARMEN", provinceCode: "13" },
  { code: "1305", name: "FLAVIO ALFARO", provinceCode: "13" },
  { code: "1306", name: "JIPIJAPA", provinceCode: "13" },
  { code: "1307", name: "JUNÍN", provinceCode: "13" },
  { code: "1308", name: "MANTA", provinceCode: "13" },
  { code: "1309", name: "MONTECRISTI", provinceCode: "13" },
  { code: "1310", name: "PAJÁN", provinceCode: "13" },
  { code: "1311", name: "PICHINCHA", provinceCode: "13" },
  { code: "1312", name: "ROCAFUERTE", provinceCode: "13" },
  { code: "1313", name: "SANTA ANA", provinceCode: "13" },
  { code: "1314", name: "SUCRE", provinceCode: "13" },
  { code: "1315", name: "TOSAGUA", provinceCode: "13" },
  { code: "1316", name: "24 DE MAYO", provinceCode: "13" },
  { code: "1317", name: "PEDERNALES", provinceCode: "13" },
  { code: "1318", name: "OLMEDO", provinceCode: "13" },
  { code: "1319", name: "PUERTO LÓPEZ", provinceCode: "13" },
  { code: "1320", name: "JAMA", provinceCode: "13" },
  { code: "1321", name: "JARAMIJÓ", provinceCode: "13" },
  { code: "1322", name: "SAN VICENTE", provinceCode: "13" },
  { code: "1401", name: "MORONA", provinceCode: "14" },
  { code: "1402", name: "GUALAQUIZA", provinceCode: "14" },
  { code: "1403", name: "LIMÓN INDANZA", provinceCode: "14" },
  { code: "1404", name: "PALORA", provinceCode: "14" },
  { code: "1405", name: "SANTIAGO", provinceCode: "14" },
  { code: "1406", name: "SUCÚA", provinceCode: "14" },
  { code: "1407", name: "HUAMBOYA", provinceCode: "14" },
  { code: "1408", name: "SAN JUAN BOSCO", provinceCode: "14" },
  { code: "1409", name: "TAISHA", provinceCode: "14" },
  { code: "1410", name: "LOGROÑO", provinceCode: "14" },
  { code: "1411", name: "PABLO SEXTO", provinceCode: "14" },
  { code: "1412", name: "TIWINTZA", provinceCode: "14" },
  { code: "1501", name: "TENA", provinceCode: "15" },
  { code: "1503", name: "ARCHIDONA", provinceCode: "15" },
  { code: "1504", name: "EL CHACO", provinceCode: "15" },
  { code: "1507", name: "QUIJOS", provinceCode: "15" },
  { code: "1509", name: "CARLOS JULIO AROSEMENA TOLA", provinceCode: "15" },
  { code: "1601", name: "PASTAZA", provinceCode: "16" },
  { code: "1602", name: "MERA", provinceCode: "16" },
  { code: "1603", name: "SANTA CLARA", provinceCode: "16" },
  { code: "1604", name: "ARAJUNO", provinceCode: "16" },
  { code: "1701", name: "DISTRITO METROPOLITANO DE QUITO", provinceCode: "17" },
  { code: "1702", name: "CAYAMBE", provinceCode: "17" },
  { code: "1703", name: "MEJÍA", provinceCode: "17" },
  { code: "1704", name: "PEDRO MONCAYO", provinceCode: "17" },
  { code: "1705", name: "RUMIÑAHUI", provinceCode: "17" },
  { code: "1707", name: "SAN MIGUEL DE LOS BANCOS", provinceCode: "17" },
  { code: "1708", name: "PEDRO VICENTE MALDONADO", provinceCode: "17" },
  { code: "1709", name: "PUERTO QUITO", provinceCode: "17" },
  { code: "1801", name: "AMBATO", provinceCode: "18" },
  { code: "1802", name: "BAÑOS DE AGUA SANTA", provinceCode: "18" },
  { code: "1803", name: "CEVALLOS", provinceCode: "18" },
  { code: "1804", name: "MOCHA", provinceCode: "18" },
  { code: "1805", name: "PATATE", provinceCode: "18" },
  { code: "1806", name: "QUERO", provinceCode: "18" },
  { code: "1807", name: "SAN PEDRO DE PELILEO", provinceCode: "18" },
  { code: "1808", name: "SANTIAGO DE PÍLLARO", provinceCode: "18" },
  { code: "1809", name: "TISALEO", provinceCode: "18" },
  { code: "1901", name: "ZAMORA", provinceCode: "19" },
  { code: "1902", name: "CHINCHIPE", provinceCode: "19" },
  { code: "1903", name: "NANGARITZA", provinceCode: "19" },
  { code: "1904", name: "YACUAMBI", provinceCode: "19" },
  { code: "1905", name: "YANTZAZA", provinceCode: "19" },
  { code: "1906", name: "EL PANGUI", provinceCode: "19" },
  { code: "1907", name: "CENTINELA DEL CÓNDOR", provinceCode: "19" },
  { code: "1908", name: "PALANDA", provinceCode: "19" },
  { code: "1909", name: "PAQUISHA", provinceCode: "19" },
  { code: "2001", name: "SAN CRISTÓBAL", provinceCode: "20" },
  { code: "2002", name: "ISABELA", provinceCode: "20" },
  { code: "2003", name: "SANTA CRUZ", provinceCode: "20" },
  { code: "2101", name: "LAGO AGRIO", provinceCode: "21" },
  { code: "2102", name: "GONZALO PIZARRO", provinceCode: "21" },
  { code: "2103", name: "PUTUMAYO", provinceCode: "21" },
  { code: "2104", name: "SHUSHUFINDI", provinceCode: "21" },
  { code: "2105", name: "SUCUMBÍOS", provinceCode: "21" },
  { code: "2106", name: "CASCALES", provinceCode: "21" },
  { code: "2107", name: "CUYABENO", provinceCode: "21" },
  { code: "2201", name: "FRANCISCO DE ORELLANA", provinceCode: "22" },
  { code: "2202", name: "AGUARICO", provinceCode: "22" },
  { code: "2203", name: "LA JOYA DE LOS SACHAS", provinceCode: "22" },
  { code: "2204", name: "LORETO", provinceCode: "22" },
  { code: "2301", name: "SANTO DOMINGO", provinceCode: "23" },
  { code: "2302", name: "LA CONCORDIA", provinceCode: "23" },
  { code: "2401", name: "SANTA ELENA", provinceCode: "24" },
  { code: "2402", name: "LA LIBERTAD", provinceCode: "24" },
  { code: "2403", name: "SALINAS", provinceCode: "24" },
];

export function getCantonsByProvinceCode(provinceCode: string): EcuadorCanton[] {
  return ECUADOR_CANTONS.filter((canton) => canton.provinceCode === provinceCode);
}
